_wandb:
    value:
        cli_version: 0.26.1
        e:
            9ma1hcr2eujrhghyyiw6905v5zbjy8du:
                args:
                    - attacker=vgsa
                    - policy=ppo
                    - +attacker.is_encoded=True
                email: thomas.ocuilleanain@pm.me
                executable: /Users/thomaoc/Projects/Misc/vgsa/.venv/bin/python
                git:
                    commit: 8dc1bb49f753959208e25e4334ba95dde3c2b549
                    remote: git@github.com:thomaoc1/vgsa.git
                host: Thomass-Mac-mini.local
                os: macOS-26.3.1-arm64-arm-64bit
                program: -m src.run_attack.run
                python: CPython 3.12.13
                root: /Users/thomaoc/Projects/Misc/vgsa
                startedAt: "2026-04-24T13:52:45.194639Z"
                writerId: 9ma1hcr2eujrhghyyiw6905v5zbjy8du
        m:
            - "1": ep_rew
              "6":
                - 3
              "7":
                - 3
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 50
            "2":
                - 1
                - 50
            "3":
                - 7
                - 16
                - 63
            "4": 3.12.13
            "5": 0.26.1
            "12": 0.26.1
            "13": darwin-arm64
action_enum_len:
    value: 1
attack_threshold:
    value: 1
attacker:
    value: vgsa
baseline_obs_dist:
    value: 2
env:
    value: PongNoFrameskip-v4
is_encoded:
    value: true
n_episodes:
    value: 100
perturbation:
    value: CW
policy:
    value: PPO
policy_seed:
    value: 0
uses_ram:
    value: false
